# Generated by Django 3.0.8 on 2020-08-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200730_0115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
